export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";


export const PRODUCT_LISTS_REQUEST = "PRODUCT_LISTS_REQUEST";
export const PRODUCT_LISTS_SUCCESS = "PRODUCT_LISTS_SUCCESS";
export const PRODUCT_LISTS_FAIL = "PRODUCT_LISTS_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST";
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";
export const PRODUCT_GET_FAIL = "PRODUCT_GET_FAIL";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";


export const PRODUCT_COUNT_REQUEST = "PRODUCT_COUNT_REQUEST";
export const PRODUCT_COUNT_SUCCESS = "PRODUCT_COUNT_SUCCESS";
export const PRODUCT_COUNT_FAIL = "PRODUCT_COUNT_FAIL";



export const PRODUCT_UPDATE_STAR_REQUEST = "PRODUCT_UPDATE_STAR_REQUEST";
export const PRODUCT_UPDATE_STAR_SUCCESS = "PRODUCT_UPDATE_STAR_SUCCESS";
export const PRODUCT_UPDATE_STAR_FAIL = "PRODUCT_UPDATE_STAR_FAIL";
export const PRODUCT_UPDATE_STAR_RESET = "PRODUCT_UPDATE_STAR_RESET";
